backend:
  name: git-gateway
  branch: main

site_url: https://griffonne.netlify.app/
display_url: https://griffonne.netlify.app/
logo_url: https://griffonne.netlify.app/IMG/Logo-Griffonne.svg

locale: 'fr'

media_library:
  name: uploadcare

publish_mode: editorial_workflow

media_folder: "/IMG"

collections:
  - name: "réalisations"
    label: "réalisations"
    folder: "/realisations"
    create: true
    fields:
      - { name: "Titre", widget: "string" }
      - { name: "Image", widget: "image" }
      - { name: "truc", widget: "map" }
      - { name: "Description", widget: "markdown" }

