backend:
  name: git-gateway
  branch: main

site_url: https://griffonne.netlify.app/
display_url: https://griffonne.netlify.app/
logo_url: https://griffonne.netlify.app/IMG/Logo-Griffonne.svg

locale: 'fr'

media_library:
  name: uploadcare

media_folder: "/IMG"

collections:
  - name: "realisation"
    label: "realisations"
    folder: "/realisations"
    create: true
    slug: "{{titre}}"
    fields:
      - {label: "Titre", name: "Réalisations", widget: "string"}
      - {label: "Realisations", name: "Realisations", description: "Mettez ici toutes vos réalisations" widget: "markdown"}

