backend:
  name: git-gateway
  branch: main

site_url: https://griffonne.netlify.app/
display_url: https://griffonne.netlify.app/
logo_url: https://griffonne.netlify.app/IMG/Logo-Griffonne.svg

locale: 'fr'

media_library:
  name: uploadcare

media_folder: "/IMG"

collections:
  - name: "realisation"
    label: "Réalisations"
    folder: "/realisations"
    create: true
    slug: "Réalisations"
    fields:
      - {label: "Realisations", name: "Realisations", widget: "markdown"}

