backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "/IMG"

collections:
  - name: "réalisations"
    label: "toutes les réalisations"
    folder: "/admin"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }

